// Generated by https://quicktype.io

export interface IRegisterResponse {
    access_token: string;
    user:         User;
}

export interface User {
    id:    number;
    email: string;
    name:  string;
}
