// Generated by https://quicktype.io

export interface IGetTasksResponse {
    id:          number;
    title:       string;
    description: string;
    completed:   boolean;
    priority:    string;
    dueDate:     Date;
    userId:      number;
    createdAt:   Date;
    updatedAt:   Date;
    user:        User;
}

export interface User {
    id:    number;
    email: string;
    name:  string;
}
