services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Opcional: montar scripts de inicialización
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Opcional: Adminer para gestión de base de datos via web
  adminer:
    image: adminer
    container_name: myapp_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
